services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.4.7
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
